version: "3.8"
services:
  db:
    image: postgres:15
    container_name: nest-postgres-db
    restart: always
    environment:
      POSTGRES_USER: user_nest
      POSTGRES_PASSWORD: password_nest
      POSTGRES_DB: db_nest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
